title: Bright Stove
email: bstovej@gmail.com
description: >-
  Reflecting information risk journey
baseurl: ""
url: "https://brightstove.net"
github_username: bstovej
timezone: Asia/Singapore
future: true

# Analytics
umami_website_id: "c5c8299c-9185-43ea-8069-f90f125f2de3"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Layout settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
